import React from 'react';
import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';
import { useRouter } from 'next/router';
import navLinks from '@component/Constants/navLinks';
import { ZweidevsLogo } from '@component/assets';
import styles from "./header.module.css"

function Header({ metaName = "description", metaContent = "Generated by create next app" }) {
    const route = useRouter();
    return (
        <>
            <Head>
                <title>Zweidevs</title>
                <meta name={metaName} content={metaContent} />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className={styles.headerContainer} >
                <Image src={ZweidevsLogo} alt="zweidevs logo" />
                <div className={styles.contentContainer} >
                    <div className={styles.pagesContainer} >
                        {navLinks.map(({ href, text }) => (
                            <Link
                                key={href}
                                href={href}
                                className={route.pathname === href && styles.activePage}
                            >
                                {text}
                            </Link>
                        ))}
                    </div>
                    <Link href={""} className={styles.instantBookingBtn} >INSTANT BOOKING</Link>
                </div>
            </div>
        </>

    )
}

export default Header;
